pywinbtrfs

diff --git a/.github/workflows/windows-build-test.yml b/.github/workflows/windows-build-test.yml
--- a/.github/workflows/windows-build-test.yml
+++ b/.github/workflows/windows-build-test.yml
@@ -2142,3 +2142,431 @@ jobs:
 
 
 
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# This is a basic workflow to help you get started with Actions
+# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
+
+  test6_pywinbtrfs:
+    needs: [build_windows] #, build_wsl]
+    timeout-minutes: 30
+    runs-on: windows-latest
+#    if:  ${{ inputs.run-failing }}
+    steps:
+
+    - uses: actions/checkout@v3
+
+
+    - uses: actions/download-artifact@v3
+      with:
+        name: dev_build_inno
+
+#    - uses: actions/download-artifact@v3
+#      with:
+#        name: build result
+
+#    - name: get files
+#      run: Get-ChildItem -Recurse
+
+    - name: get diskdrive
+      run: wmic diskdrive list
+
+#    - name: Download
+#      uses: suisei-cn/actions-download-file@v1.3.0
+#      #id: innoinstaller
+#      with:
+#        url: 'https://github.com/andrewc12/zfsfiledump/raw/main/testdrives.zip'
+#        target: ${{github.workspace}}/
+#
+#
+#    - name: make disk
+#      run: |
+#        Expand-Archive -LiteralPath ${{github.workspace}}/testdrives.zip -DestinationPath D:\
+#
+#    - name: Download
+#      uses: suisei-cn/actions-download-file@v1.3.0
+#      #id: innoinstaller
+#      with:
+#        url: 'https://github.com/andrewc12/zfsfiledump/raw/main/scriptname.txt'
+#        target: ${{github.workspace}}/
+#
+#    - name: make disk
+#      run: |
+#        diskpart /s scriptname.txt
+#
+#
+#
+#    - name: get diskdrive
+#      run: wmic diskdrive list
+#
+#
+#    - name: get files
+#      run: Get-ChildItem -Recurse
+
+
+    - name: get zfsexename
+      id: zfsinstaller
+      run: |
+        $p = Get-ChildItem | Where-Object {$_.Name -like 'OpenZFSOnWindows-*.exe'} | Select-Object -first 1
+        echo $p
+        $f = (Get-Item $p ).Name
+        echo $f
+        echo "filename=$f" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
+
+    # https://github.com/MicrosoftDocs/windows-powershell-docs/issues/266
+    - name: Import root certificate
+      run: |
+        $plaintextpwd = 'password1234'
+        $pwd = ConvertTo-SecureString -String $plaintextpwd -Force -AsPlainText
+        Import-PfxCertificate -FilePath ${{github.workspace}}/contrib/windows/TestCert/test_sign_cert_pass.pfx -CertStoreLocation Cert:\LocalMachine\Root -Password $pwd
+        Import-PfxCertificate -FilePath ${{github.workspace}}/contrib/windows/TestCert/test_sign_cert_pass.pfx -CertStoreLocation Cert:\LocalMachine\TrustedPublisher -Password $pwd
+
+    - name: debug - echo filename
+      run: echo ${{ steps.zfsinstaller.outputs.filename }}
+
+#    - name: debug - list
+#      run: ls ${{github.workspace}}\
+
+    - name: debug - list
+      run: ls ${{github.workspace}}\${{ steps.zfsinstaller.outputs.filename }}
+
+    #- name: install zfs
+    #  run: ${{github.workspace}}\${{ steps.zfsinstaller.outputs.filename }} /NORESTART /ALLUSERS /VERYSILENT /LOG="${{github.workspace}}\InnoSetup-Install.log"
+
+    - name: install zfs
+      run: 'Start-Process -FilePath "${{github.workspace}}\${{ steps.zfsinstaller.outputs.filename }}" -Wait -ArgumentList "/NORESTART /ALLUSERS /VERYSILENT /LOG=`"${{github.workspace}}\InnoSetup-Install.log`""'
+
+    #- name: Wait for install to finish
+    #  run: Start-Sleep -Seconds 30
+    #  uses: iFaxity/wait-on-action@v1
+    #  with:
+    #    resource: 'C:\Program Files\OpenZFS On Windows\zpool.exe'
+
+#    - name: debug - print log
+#      run: cat "${{github.workspace}}\InnoSetup-Install.log"
+#
+#    - name: debug - list
+#      run: ls "C:\Program Files"
+#
+#    - name: debug - list
+#      run: ls "C:\Program Files\OpenZFS On Windows"
+
+    - name: debug - get status
+      run: '& "C:\Program Files\OpenZFS On Windows\zpool.exe" status'
+
+
+
+
+
+
+
+    - name: Download winbtrfs
+      uses: suisei-cn/actions-download-file@v1.3.0
+      id: winbtrs  # Remember to give an ID if you need the output filename
+      with:
+        url: "https://github.com/andrewc12/btrfs/releases/download/v1.8/x64-Debug.zip"
+        target: ${{github.workspace}}/
+
+    - name: extract
+      run: Expand-Archive -LiteralPath '${{ steps.winbtrs.outputs.filename }}' -DestinationPath ${{github.workspace}}\winbtrfs
+
+    - name: debug - list
+      run: ls ${{github.workspace}}\
+
+    - name: debug - list
+      run: ls ${{github.workspace}}\winbtrfs
+
+
+
+
+
+
+
+
+    - name: test
+      run: 'python.exe -u "${{github.workspace}}\contrib\windows\tests\btrfstests.py" -path ${{github.workspace}}\'
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+    #- name: run winbtrfs tests
+    #  run: '& "${{github.workspace}}\winbtrfs\test.exe" ${{ steps.drive.outputs.drive }}'
+
+    - name: test dummy status step
+      id: dummy
+      run: exit 0
+
+    - name: debug - dummy status
+      run: echo ${{ steps.dummy.conclusion }}
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    #https://github.com/maharmstone/btrfs/blob/master/src/tests/test.cpp#L453
+    - name: run winbtrfs create tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" create ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs supersede tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" supersede ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs overwrite tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" overwrite ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs open_id tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" open_id ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs io tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" io ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs mmap tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" mmap ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs rename tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" rename ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs rename_ex tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" rename_ex ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs delete tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" delete ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs delete_ex tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" delete_ex ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs links tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" links ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs links_ex tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" links_ex ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_i tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_i ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_ii tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_ii ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_batch tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_batch ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_filter tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_filter ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_r tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_r ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_rw tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_rw ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_rh tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_rh ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs oplock_rwh tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" oplock_rwh ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs cs tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" cs ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs reparse tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" reparse ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs streams tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" streams ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    #- name: run winbtrfs ea tests
+    #  if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+    #  run: '& "${{github.workspace}}\winbtrfs\test.exe" ea ${{ steps.drive.outputs.drive }}'
+
+    - name: run winbtrfs fileinfo tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" fileinfo ${{ steps.drive.outputs.drive }}'
+
+    - run: Start-Sleep -Seconds 10
+      timeout-minutes: 1
+
+    - name: run winbtrfs ea tests
+      if: ${{ ( success() || failure() ) && steps.dummy.conclusion == 'success' }}
+      timeout-minutes: 1
+      run: '& "${{github.workspace}}\winbtrfs\test.exe" ea ${{ steps.drive.outputs.drive }}'
+
+    #- name: run export zpool
+    #  if: ${{ always() }}
+    #  timeout-minutes: 1
+    #  run: '& "C:\Program Files\OpenZFS On Windows\zpool.exe" export tank'
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
